FROM mileschou/lua:%%LUA_VERSION%%

LABEL repository="https://github.com/MilesChou/lua-action" \
    maintainer="MilesChou <jangconan@gmail.com>"

COPY lua-entrypoint /usr/local/bin/lua-entrypoint

ENTRYPOINT ["/usr/local/bin/lua-entrypoint"]
